spring:
  application:
    name: core-billing
  profiles:
    active: sqlite
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    hikari:
      initialization-fail-timeout: -1

server:
  port: ${SERVER_PORT:8102}

logging:
  level:
    io.coreplatform.billing: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always